"""Add bulk request and pledge models

Revision ID: 67bd71084a8d
Revises: cfa0cc349689
Create Date: 2025-07-12 15:23:30.532802+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bd71084a8d'
down_revision: Union[str, None] = 'cfa0cc349689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('quantity_needed', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('max_price_per_unit', sa.Float(), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('delivery_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_location', sa.String(length=500), nullable=False),
    sa.Column('delivery_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_FILLED', 'FULLY_FILLED', 'CLOSED', 'EXPIRED', name='bulkrequeststatus'), nullable=False),
    sa.Column('quantity_pledged', sa.Float(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_request_pledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity_pledged', sa.Float(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('estimated_delivery_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'FULFILLED', 'CANCELLED', name='pledgestatus'), nullable=False),
    sa.Column('bulk_request_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bulk_request_id'], ['bulk_request.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('bulk_request_pledge')
    op.drop_table('bulk_request')
    # ### end Alembic commands ###
